extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/prof_plewis
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/r/proflewis/geog0111
  - icon: fontawesome/brands/github
    link: https://github.com/UCL-EO/geog0111
google_analytics:
- UA-1347772-1
- auto
nav:
- 000_Running_options.md
- 001_Notebook_use.md
- 003_Local_Install.md
- 005_Help.md
- 010_Python_Introduction.md
- 011_Python_data_types.md
- 012_Python_strings.md
- 013_Python_string_methods.md
- 014_Python_groups.md
- 015_Python_control.md
- 016_Python_for.md
- 017_Functions.md
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
extra_javascript:
- javascripts/config.js
plugins:
- git-revision-date-localized
- exclude:
    glob:
      - "*blank.tif"
      - "*.pyc"
      - "data/Hydrologic_Units/HUC_Lines*"
      - "geog0111/__pycache__/*"
      - "work/*"
      - "__pycache__"
      - "*.bin"
      - "*.hdf"
      - "*.store"
      - "*.nc"
      - "*.zip"
      - "*.npz"
      - "data/ucl/*"
      - "*.vrt"

repo_url: https://github.com/UCL-EO/geog0111
site_author: Prof P. Lewis
site_name: GEOG0111
theme:
  logo: images/ucl.png
  favicon: images/ucl.png
  name: material
